[package]
org = "wso2"
name = "medical_center"
version = "0.1.0"

[[dependency]]
org = "ballerina"
name = "persist"
version = "0.1.0"
repository = "local"

[persist.medical_center.storage.mysql]
host = "localhost"
port = 3305
user = "root"
password = "Test123#"
database = "medical_center_db"

