[package]
org = "wso2"
name = "medical_center"
version = "0.1.0"

[persist]
datastore = "mysql"
module = "medical_center"

[[dependency]]
org = "ballerina"
name = "persist"
version = "0.3.1"
repository = "local"

[[platform.java11.dependency]]
groupId = "io.ballerina.persist"
artifactId = "persist-native"
version = "0.3.1"
path = "../../native/build/libs/persist-native-0.3.1-SNAPSHOT.jar"
