[package]
org = "ballerina"
name = "persist"
version = "0.2.3"
authors = ["Ballerina"]
keywords = ["persist", "experimental"]
repository = "https://github.com/ballerina-platform/module-ballerina-persist"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.persist"
artifactId = "persist-native"
version = "0.2.3"
path = "../native/build/libs/persist-native-0.2.3-SNAPSHOT.jar"
