[package]
org = "ballerina"
name = "persist"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["persist"]
repository = "https://github.com/ballerina-platform/module-ballerina-persist"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.persist"
artifactId = "persist-native"
version = "1.0.0"
path = "../native/build/libs/persist-native-1.0.0.jar"
