[package]
org = "ballerina"
name = "persist"
version = "1.1.1"
authors = ["Ballerina"]
keywords = ["persist"]
repository = "https://github.com/ballerina-platform/module-ballerina-persist"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.persist"
artifactId = "persist-native"
version = "1.1.1"
path = "../native/build/libs/persist-native-1.1.1-SNAPSHOT.jar"
